"""currency refactor

Revision ID: 33cb8c601ced
Revises: d079efbef80c
Create Date: 2025-10-06 16:39:04.039551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cb8c601ced'
down_revision: Union[str, Sequence[str], None] = 'd079efbef80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('currency', sa.Float(), nullable=True))
    op.alter_column('incomes', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('incomes', 'is_rub')
    op.drop_column('incomes', 'is_euro')
    op.drop_column('incomes', 'is_rsd')
    op.add_column('purchases', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('purchases', 'is_rub')
    op.drop_column('purchases', 'is_active')
    op.drop_column('purchases', 'is_euro')
    op.drop_column('purchases', 'is_rsd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('is_rsd', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('is_euro', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('is_rub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('purchases', 'currency')
    op.add_column('incomes', sa.Column('is_rsd', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('incomes', sa.Column('is_euro', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('incomes', sa.Column('is_rub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('incomes', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('incomes', 'currency')
    # ### end Alembic commands ###
