name: CI/CD — Build, Test, Push to GHCR

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_BASE: ghcr.io/rozzenrose/report_builder
      IMAGE: ghcr.io/rozzenrose/report_builder:${{ github.sha }}

    steps:
      # 1️ Клонируем код
      - name: Checkout
        uses: actions/checkout@v4

      # 2 Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3 Логинимся в GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4 Подтягиваем образы зависимостей
      - name: Pull dependency images
        run: |
          docker pull ghcr.io/rozzenrose/currency_aggregator:latest || true
          docker pull ghcr.io/rozzenrose/report_builder:latest || true

      # 5 Сборка образа основного сервиса
      - name: Build main service image
        run: docker build -t "$IMAGE" .

      # 6 Прогон тестов внутри локального образа
      - name: Run tests
        run: docker run --rm "$IMAGE" python -m pytest

      # 7️ Публикуем образ в GHCR (только для main)
      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE $IMAGE_BASE:${{ github.sha }}
          docker tag $IMAGE $IMAGE_BASE:latest
          docker push $IMAGE_BASE:${{ github.sha }}
          docker push $IMAGE_BASE:latest
